name: Ejecutar pruebas unitarias
on:
    push:
        branches:
            - '!main'
    pull_request:

jobs:
    java-test:
        name: Pruebas de Java
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Setup Java and Maven
                uses: actions/setup-java@v1
                with:
                    java-version: 17
                    distribution: 'temurin'
                    java-package: jdk
                    cache: 'maven'
            -   name: Ejecutar tests
                run: mvn test -Dspring.profiles.active=test
    vue-test:
        name: Pruebas de Vue
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Setup Node.js
                uses: actions/setup-node@v3
                with:
                    node-version: '16'
                    cache: 'npm'
                    cache-dependency-path: front/package-lock.json
            -   name: Instalar dependencias
                uses: borales/actions-yarn@v4
                with:
                    cmd: install
                    dir: 'front'
            -   name: Ejecutar tests
                uses: borales/actions-yarn@v4
                with:
                    cmd: test
                    dir: 'front'